### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by fkjogu** [bsteinb/rsmpi#10]
Is it possible to profile your rsmpi using application with a MPI aware profiler like VampirTrace or Valgrind?

Excuse me, if this is not the place to ask such questions.

**Comment by bsteinb** [comment]
I just did some experiments and was able to successfully link mpiP into some of my examples. It seemed to pick up the MPI function calls performed by Rust code.

To build the examples with mpiP, I did

```
cargo rustc --verbose --example vector -- -L native=/directory/containing/libmpiP.so/ -l dylib=mpiP
```

I guess other profilers might achieve similar amounts of success. Does this answer your question?

**Comment by fkjogu** [comment]
Yes, thank you. I've tried Callgrind and VampirTrace with dynamic instrumentation, which seems to work. It would be interesting, if tools would work, that do the instrumentation on a binary level.

I probably will investigate this further. For now, I'll close this issue.

**Comment by bsteinb** [comment]
Good to know, thanks for reporting this. I would be interested to hear about the results of your further investigations also.
