### ISSUE TITLE
crabtw's bindgen repo has ceased to exist

### ISSUE THREAD

**Issue by cillian64** [bsteinb/rsmpi#15]
I cannot build current master because it depends on `https://github.com/crabtw/rust-bindgen.git?rev=0433980286a5264e3d69214aa42e314c37238cf6`.  That repository has been deleted and the only crates.io release of rust-bindgen has been yanked.

To replicate this you would need to clear out your cargo crates registry and git checkouts or try to build on a clean install of cargo which does not have rust-bindgen cached.

The `bindgen` package by servo looks like a newer version of the same base, so I assume rsmpi needs porting to use this.

**Comment by bsteinb** [comment]
Yes, I am aware. Let me see if I can whip something up.

**Comment by bsteinb** [comment]
So, I got this working a few days (maybe weeks) ago, but never pushed those changes. In the meantime that version of the `libbindgen` crate (as it was called back then) has been yanked from crates.io. The current version of `bindgen` on crates.io again does not work for `rsmpi` (https://github.com/servo/rust-bindgen/issues/509). I will push a working version using `libbindgen` from the `servo/rust-bindgen` git repo into a branch for now.

**Comment by bsteinb** [comment]
I have added a branch `bindgen-hack` that can be built for now. Not all CI tests pass at the moment. I cannot reproduce the locally at the moment, will have a look at it later.

**Comment by cillian64** [comment]
This branch seems to work correctly for me, thank-you!

**Comment by Rufflewind** [comment]
The aforementioned bindgen bug has been fixed and they have a new release now.  Is there anything else that's holding back this issue?

**Comment by bsteinb** [comment]
I have updated the `bindgen-hack` branch to use the current version of `bindgen` on crates.io. However I currently still have to work around [this issue](https://github.com/servo/rust-bindgen/issues/511). I will hold back master until this is solved.

**Comment by bsteinb** [comment]
It does not look like the `bindgen` issue is getting fixed soon, so I have marked the workaround with 'FIXME's and fast-forwarded the master branch to include these changes.
