### ISSUE TITLE
I couldn't compile example

### ISSUE THREAD

**Issue by CaptainVi** [bsteinb/rsmpi#20]
Hello!
I read the issue https://github.com/bsteinb/rsmpi/issues/15
and after that I tried to compile example "simple" from the branch rsmpi (bindgen-hack)  
But I received error:  

Compiling mpi v0.4.0 (file:///.../rsmpi)
error[E0425]: unresolved name `bindgen::get_include_dir`
  --> build.rs:43:38
   |
43 |     if let Some(clang_include_dir) = bindgen::get_include_dir() {
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^ unresolved name

error: aborting due to previous error

**Comment by bsteinb** [comment]
Hi, and thank you for reporting this. However, something seems to be amiss on your end. This is not what [line 43 in build.rs](https://github.com/bsteinb/rsmpi/blob/bindgen-hack/build.rs#L43) looks like on the `bindgen-hack` branch. Are you sure you have that branch properly checked out?
