### ISSUE TITLE
Run on several processes

### ISSUE THREAD

**Issue by CaptainVi** [bsteinb/rsmpi#21]
Hello, bsteinb!

Thanks for your previous answer on my question!!!
But I've one more Q, may be a stupid one, but important for me:
If I compiled in C then I would enter such commands to run, for example, 10 processes:
mpicc test.c –o test.o
mpirun –np 10 test.o

How can I do like this using your Lib and Rust?
For example: simple.rs run on 10 processes.

We should initialize it here, right? :
    let universe = mpi::initialize().unwrap();
    let world = universe.world();
    let size = world.size();
    let rank = world.rank();
But how?

Thanks!

**Comment by bsteinb** [comment]
Hi! I am not exactly sure what you are asking. Is it about

1. building an executable that uses `rsmpi`?  Making a new `cargo` project that pulls in `rsmpi` as a dependency is probably the easiest way.
2. running multiple processes using an executable built with `rsmpi`? That should work exactly like a C executable, `mpirun -n 10 <executable>`.
3. initializing `rsmpi`? There are several examples in the examples directory which demonstrate this.

Hope this helps.

**Comment by CaptainVi** [comment]
Ok
Thanks!
