### ISSUE TITLE
Move mpi::ffi into separate crate

### ISSUE THREAD

**Issue by AndrewGaspar** [bsteinb/rsmpi#30]
There's a couple reasons to do this -

1) For people hacking on rsmpi, it means shorter incremental compile times since bindgen doesn't have to be re-run on every compile
2) If published separately, it would allow users to just take mpi::ffi if they don't want to use rsmpi's API - they can just call MPI directly.

This is pretty low priority.

**Comment by bsteinb** [comment]
Yes, I agree. I have not taken that step yet, because I think having the two crates integrated keeps things simpler for now while rsmpi is not at 1.0 yet.

**Comment by bsteinb** [comment]
Fixed in #37, thanks a lot.
