### ISSUE TITLE
Run `cargo fmt`

### ISSUE THREAD

**Issue by AndrewGaspar** [bsteinb/rsmpi#31]
I noticed that the code is out of date with the rustfmt.toml checked in to the repo, at least with the new version of rustfmt I'm using. If may be good to run a cargo fmt at some point.

**Comment by bsteinb** [comment]
I had not taken a look at rustfmt in a while. I like the default settings, so I deleted the `rustfmt.toml` and ran the code through rustfmt in b2fcc8f328786e56153ad1bc522963a5f287ebdd.

**Comment by AndrewGaspar** [comment]
Excellent, thank you!
