### ISSUE TITLE
Consider defining `equivalent_system_datatype!(bool, ffi::RSMPI_C_BOOL);`

### ISSUE THREAD

**Issue by AndrewGaspar** [bsteinb/rsmpi#34]
It was [recently decided](https://github.com/rust-lang/rust/pull/46176#issuecomment-359593446), pending a final comment period, that Rust's `bool` will be defined as equivalent to C's `_Bool` on all platforms that Rust will ever support. Therefore, it is safe and defined behavior to add a definition of bool as using ffi:RSMPI_C_BOOL.

**Comment by bsteinb** [comment]
Fixed in #35, thanks!

**Comment by AndrewGaspar** [comment]
Any chance you could put out a version 0.5.1 with this change?

**Comment by bsteinb** [comment]
It was a bit of a struggle with my bespoke releases-are-deployed-via-travis-ci scripts, but I prevailed. Version 0.5.1 of the `mpi` crate is on crates.io and so is version 0.1.0 of `mpi-sys`.
