### ISSUE TITLE
What does the version of clang need?

### ISSUE THREAD

**Issue by CaptainVi** [bsteinb/rsmpi#38]
Hello!

I tried to compile example/simple and I had an error "thread 'main' panicked at 'function not loaded: clang_Type_getNumTemplateArguments', ../.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.21.2/src/lib.rs:1456:1"

I have:
clang version 7.0.0 (trunk 326027) (llvm/trunk 326026)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/clang/bin

On another PC I have:
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

And it works.

**Comment by bsteinb** [comment]
`rsmpi` does not use `clang`, but uses `bindgen` which in turn uses the `clang-sys` which depends on the native `libclang`.

The [`clang-sys` documentation](https://github.com/KyleMayes/clang-sys/blob/master/README.md) mentions `libclang` version 3.5 through 5.0 , so I guess those should work. On the other hand, [`bindgen` seems to depend on features in `libclang` that were introduced in version 3.9](https://github.com/rust-lang-nursery/rust-bindgen/blob/master/Cargo.toml#L47), so maybe that restricts the range of supported versions to 3.9 through 5.0. However, it looks like version 3.8 is working for you, so, yeah, I have no idea.

**Comment by AndrewGaspar** [comment]
IIRC clang 3.9 was required, though I can't remember what errors I was getting.

**Comment by AndrewGaspar** [comment]
Clang 3.9 or later
