### ISSUE TITLE
Bindgen issue 511 has already been fixed

### ISSUE THREAD

**Issue by gnzlbg** [bsteinb/rsmpi#63]
See: 

* https://github.com/bsteinb/rsmpi/blob/master/mpi-sys/src/rsmpi.h#L43
* https://github.com/bsteinb/rsmpi/blob/master/mpi-sys/src/rsmpi.c#L37

**Comment by bsteinb** [comment]
I know. However, the fix happened after the rather ancient version of `bindgen` that we have to use was released. See also #44 and the foreign issues linked therein.

**Comment by rcarson3** [comment]
@bsteinb It looks like `libffi-sys v0.6.4` has updated its `bindgen` dependency to v0.49 which should allow you to now bring `mpi-sys` up to a more modern version of `bindgen`.

**Comment by bsteinb** [comment]
@rcarson3 Thank you for the heads up. From my end it looks like I *have* to upgrade to a newer version of `bindgen` now as I currently cannot build `mpi-sys`.

**Comment by bsteinb** [comment]
Fixed in a3adac0499e273b407c0040f0da5d30c1fb223c8
