### ISSUE TITLE
Derive macro for the Equivalence trait

### ISSUE THREAD

**Issue by Davier** [bsteinb/rsmpi#71]
Hi,

I wrote a derive macro to automatically implement the `mpi::datatype::Equivalence` trait on plain structures: [rsmpi-derive](https://github.com/Davier/rsmpi_derive).
However I'm new to Rust and not experienced with MPI, so the quality may be low.

Is this a good place to share it and look for feedback?
Should I publish it on crates.io, and is it OK to use the name mpi-derive?

Regards,
Brice DAVIER

**Comment by AndrewGaspar** [comment]
Great minds think alike. :) https://github.com/bsteinb/rsmpi/pull/52

**Comment by Davier** [comment]
That's great thanks, I should have looked at the pull requests :)
